/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeServicoRouteImport } from './routes/termos-de-servico'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as ApiPublicTiktokCallbackRouteImport } from './routes/api/public/tiktok/callback'
import { Route as ApiPublicPushSubscribeRouteImport } from './routes/api/public/push/subscribe'
import { Route as ApiPublicHooksCheckLiveRouteImport } from './routes/api/public/hooks/check-live'

const TermosDeServicoRoute = TermosDeServicoRouteImport.update({
  id: '/termos-de-servico',
  path: '/termos-de-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTiktokCallbackRoute = ApiPublicTiktokCallbackRouteImport.update({
  id: '/api/public/tiktok/callback',
  path: '/api/public/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushSubscribeRoute = ApiPublicPushSubscribeRouteImport.update({
  id: '/api/public/push/subscribe',
  path: '/api/public/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckLiveRoute = ApiPublicHooksCheckLiveRouteImport.update({
  id: '/api/public/hooks/check-live',
  path: '/api/public/hooks/check-live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ferramentas': typeof FerramentasRoute
  '/galeria': typeof GaleriaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/chat': typeof AuthenticatedChatRoute
  '/conta': typeof AuthenticatedContaRoute
  '/api/public/hooks/check-live': typeof ApiPublicHooksCheckLiveRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ferramentas': typeof FerramentasRoute
  '/galeria': typeof GaleriaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/chat': typeof AuthenticatedChatRoute
  '/conta': typeof AuthenticatedContaRoute
  '/api/public/hooks/check-live': typeof ApiPublicHooksCheckLiveRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/ferramentas': typeof FerramentasRoute
  '/galeria': typeof GaleriaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/api/public/hooks/check-live': typeof ApiPublicHooksCheckLiveRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ferramentas'
    | '/galeria'
    | '/politica-de-privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/termos-de-servico'
    | '/chat'
    | '/conta'
    | '/api/public/hooks/check-live'
    | '/api/public/push/subscribe'
    | '/api/public/tiktok/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ferramentas'
    | '/galeria'
    | '/politica-de-privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/termos-de-servico'
    | '/chat'
    | '/conta'
    | '/api/public/hooks/check-live'
    | '/api/public/push/subscribe'
    | '/api/public/tiktok/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/ferramentas'
    | '/galeria'
    | '/politica-de-privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/termos-de-servico'
    | '/_authenticated/chat'
    | '/_authenticated/conta'
    | '/api/public/hooks/check-live'
    | '/api/public/push/subscribe'
    | '/api/public/tiktok/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FerramentasRoute: typeof FerramentasRoute
  GaleriaRoute: typeof GaleriaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosDeServicoRoute: typeof TermosDeServicoRoute
  ApiPublicHooksCheckLiveRoute: typeof ApiPublicHooksCheckLiveRoute
  ApiPublicPushSubscribeRoute: typeof ApiPublicPushSubscribeRoute
  ApiPublicTiktokCallbackRoute: typeof ApiPublicTiktokCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-servico': {
      id: '/termos-de-servico'
      path: '/termos-de-servico'
      fullPath: '/termos-de-servico'
      preLoaderRoute: typeof TermosDeServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/tiktok/callback': {
      id: '/api/public/tiktok/callback'
      path: '/api/public/tiktok/callback'
      fullPath: '/api/public/tiktok/callback'
      preLoaderRoute: typeof ApiPublicTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/subscribe': {
      id: '/api/public/push/subscribe'
      path: '/api/public/push/subscribe'
      fullPath: '/api/public/push/subscribe'
      preLoaderRoute: typeof ApiPublicPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-live': {
      id: '/api/public/hooks/check-live'
      path: '/api/public/hooks/check-live'
      fullPath: '/api/public/hooks/check-live'
      preLoaderRoute: typeof ApiPublicHooksCheckLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FerramentasRoute: FerramentasRoute,
  GaleriaRoute: GaleriaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosDeServicoRoute: TermosDeServicoRoute,
  ApiPublicHooksCheckLiveRoute: ApiPublicHooksCheckLiveRoute,
  ApiPublicPushSubscribeRoute: ApiPublicPushSubscribeRoute,
  ApiPublicTiktokCallbackRoute: ApiPublicTiktokCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
