/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTiktokCallbackRouteImport } from './routes/api/public/tiktok/callback'
import { Route as ApiPublicPushSubscribeRouteImport } from './routes/api/public/push/subscribe'
import { Route as ApiPublicHooksCheckLiveRouteImport } from './routes/api/public/hooks/check-live'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTiktokCallbackRoute = ApiPublicTiktokCallbackRouteImport.update({
  id: '/api/public/tiktok/callback',
  path: '/api/public/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushSubscribeRoute = ApiPublicPushSubscribeRouteImport.update({
  id: '/api/public/push/subscribe',
  path: '/api/public/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckLiveRoute = ApiPublicHooksCheckLiveRouteImport.update({
  id: '/api/public/hooks/check-live',
  path: '/api/public/hooks/check-live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/ferramentas': typeof FerramentasRoute
  '/galeria': typeof GaleriaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/hooks/check-live': typeof ApiPublicHooksCheckLiveRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/ferramentas': typeof FerramentasRoute
  '/galeria': typeof GaleriaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/hooks/check-live': typeof ApiPublicHooksCheckLiveRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/ferramentas': typeof FerramentasRoute
  '/galeria': typeof GaleriaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/hooks/check-live': typeof ApiPublicHooksCheckLiveRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/ferramentas'
    | '/galeria'
    | '/sitemap.xml'
    | '/api/public/hooks/check-live'
    | '/api/public/push/subscribe'
    | '/api/public/tiktok/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/ferramentas'
    | '/galeria'
    | '/sitemap.xml'
    | '/api/public/hooks/check-live'
    | '/api/public/push/subscribe'
    | '/api/public/tiktok/callback'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/ferramentas'
    | '/galeria'
    | '/sitemap.xml'
    | '/api/public/hooks/check-live'
    | '/api/public/push/subscribe'
    | '/api/public/tiktok/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FerramentasRoute: typeof FerramentasRoute
  GaleriaRoute: typeof GaleriaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksCheckLiveRoute: typeof ApiPublicHooksCheckLiveRoute
  ApiPublicPushSubscribeRoute: typeof ApiPublicPushSubscribeRoute
  ApiPublicTiktokCallbackRoute: typeof ApiPublicTiktokCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiktok/callback': {
      id: '/api/public/tiktok/callback'
      path: '/api/public/tiktok/callback'
      fullPath: '/api/public/tiktok/callback'
      preLoaderRoute: typeof ApiPublicTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/subscribe': {
      id: '/api/public/push/subscribe'
      path: '/api/public/push/subscribe'
      fullPath: '/api/public/push/subscribe'
      preLoaderRoute: typeof ApiPublicPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-live': {
      id: '/api/public/hooks/check-live'
      path: '/api/public/hooks/check-live'
      fullPath: '/api/public/hooks/check-live'
      preLoaderRoute: typeof ApiPublicHooksCheckLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FerramentasRoute: FerramentasRoute,
  GaleriaRoute: GaleriaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksCheckLiveRoute: ApiPublicHooksCheckLiveRoute,
  ApiPublicPushSubscribeRoute: ApiPublicPushSubscribeRoute,
  ApiPublicTiktokCallbackRoute: ApiPublicTiktokCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
